name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
  build:
  
    runs-on: ubuntu-latest
    needs: cypress-run

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: 
        username: ${{ secrets.DOCKERHUB_NAME }}
        password: ${{ secrets.DOCKERHUB_PWD }}
        
    - name: Build and push container image to repository
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_NAME }}/tp-devops:${{ github.sha }}
        file: ./Dockerfile

  deploy-preview:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
      url: ${{ steps.deploy-preview.outputs.app-url }}
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CHREDENTIAL}}
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: 'Deploy to Azure Container Instances'
      id: deploy-preview 
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: tvictorien_group
        dns-name-label: ${{ env.GITHUB_HEAD_REF_SLUG}}-tvictorien
        image: ${{ secrets.DOCKERHUB_NAME }}/tp-devops:${{ github.sha }}
        name: tvictorien-${{ env.GITHUB_HEAD_REF_SLUG}}
        location: 'francecentral'
        registry-username: ${{ secrets.DOCKERHUB_NAME }}
        registry-password: ${{ secrets.DOCKERHUB_PWD }}
        registry-login-server: index.docker.io
        ports: 3000
   
  